package org.kyll.common.type;

public enum ClazzType {
	BYTE, SHORT, INT, LONG, FLOAT, DOUBLE, CHAR, BOOLEAN, STRING, DATE, UPLOADFILE, OBJECT,
	BYTE_ARRAY, SHORT_ARRAY, INT_ARRAY, LONG_ARRAY, FLOAT_ARRAY, DOUBLE_ARRAY, CHAR_ARRAY, BOOLEAN_ARRAY, STRING_ARRAY,
	ARRAY, LIST, SET, MAP
}
